### ISSUE TITLE
Separate Auth Backend Sources from UI Package

### ISSUE THREAD

**Issue by slavarazum** [laravel/ui#88]
Auth sources has been moved to Laravel UI package. I think it's kind of misconception.
In support of this we have autoloading for `Illuminate\Foundation\Auth` namespace in this package:
```
"Illuminate\\Foundation\\Auth\\": "auth-backend/"
```

**Use case**: If we want to use this auth logic with Sanctum we forced to install laravel/ui, but we needn't any UI presets.

Authentication !== UI

**Comment by driesvints** [comment]
No plans to change this.

**Comment by guianzollin** [comment]
> Auth sources has been moved to Laravel UI package. I think it's kind of misconception.
> In support of this we have autoloading for `Illuminate\Foundation\Auth` namespace in this package:
> 
> ```
> "Illuminate\\Foundation\\Auth\\": "auth-backend/"
> ```
> 
> **Use case**: If we want to use this auth logic with Sanctum we forced to install laravel/ui, but we needn't any UI presets.
> 
> Authentication !== UI


I agree

**Comment by CImrie** [comment]
I just had this issue as well - I removed the boilerplate frontend code that comes with a fresh install (including the`variables.scss` file) and the `php artisan ui vue --auth` command failed because it couldn't find the expected boilerplate files. So have resorted to implementing my own `LoginController`.

I'm also using Svelte, so vue/bootstrap/react presets just don't make sense for an agnostic backend.
